spring:
  thymeleaf:
    cache: false
    #非严格模式的HTML语法检查
    mode: LEGACYHTML5
  aop:
    proxy-target-class: true
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
  cache:
    ehcache:
      config: ehcache/ehcache.xml